# config.yaml
# Configuration for When Cham We Meet.

gcp:
  project: when-cham-we-meet

firebase:
  api_key: ""
  auth_domain: ""
  project_id: ""
  storage_bucket: ""
  messaging_sender_id: ""
  app_id: ""
